### PR TITLE
Actually make it so we can disable streaming...

### PR DESCRIPTION
**Pull request by d8ahazard**
Right now, it's always setting active to "true". This is problematic when I want to try stopping a stream without waiting 10s. :D

### CODE REVIEW

**Comment by michielpost** [comment]
Thanks!

**Comment by d8ahazard** [comment]
Awesome!

As I'm not too familiar with how the .net package system works...when will this trickle it's way down into the version of the lib I'm using via NuGet?

**Comment by michielpost** [comment]
It's already on NuGet in version 3.12.1
https://www.nuget.org/packages/Q42.HueApi/3.12.1

**Comment by d8ahazard** [comment]
Nice! Thanks!

**Pull request merged**
