### PR TITLE
Build net462 by default

### LINKED ISSUE #123: Install in .net 4.6.2 project
Why when i'm installing in .net 4.6.2. project, install everything of .net standard library?

### PR DESCRIPTION
**Pull request by leo60228**
Fixes #123.

### CODE REVIEW

**Comment by michielpost** [comment]
Hi,

Thanks for your PR. But the Q42.HueApi.Streaming project does not build for .Net45
It doesn't know about `Task.CompletedTask` and also `_socket.ConnectAsync` has different paremeters in .net45.
Can you fix it so it build correctly?

Thanks!

**Comment by leo60228** [comment]
That's weird, it built for me. Looking at MSDN, it seems like those existed in .NET 4.5. Even then, isn't this library supposed to be compatible with .NET 4.5? For my uses, I only need .NET 4.7, I just chose 4.5 because of the README.

**Comment by michielpost** [comment]
The library targets .netstandard2.0, it's the way to go for modern .net development. If somebody needs additional frameworks and I can provide that without code changes, that's fine. But I won't put much effort in supporting legacy platforms.
.NET 4.7.1 supports .netstandard2.0 packages, so including the net471 target is useless I think.

Thanks for pointing me to the readme, it contains a lot of outdated info. I'll update that.

**Comment by leo60228** [comment]
.NET 4.7.1 supports netstandard2.0, yes, but it still pulls in several libraries from NuGet. For my usecase, it would be much more useful if I only needed to pull in Newtonsoft.Json and the 3 Q42.HueApi libraries.

**Comment by leo60228** [comment]
Since for some reason .NET 4.5 built locally, even though it didn't on CI, I'm going to just bump the version until it works on CI, if that's okay with you.

**Comment by leo60228** [comment]
Looks like it builds fine now. Though you might want to test it; not sure if I used SocketAsyncEventArgs correctly.

**Comment by michielpost** [comment]
Ok, so what if we target .net45 for the Q42.HueApi and ColorConverters project and .net471 for the Streaming project? That way .net45 is supported for the main project and if you want to use the Entertainment API you'll need at least .net471. And then we can leave the cleaner ConnectAsync as it is.

**Comment by leo60228** [comment]
Okay, I'll do that.

**Comment by michielpost** [comment]
Thanks. Packages are published to NuGet with version 3.10.0

**Pull request merged**
