### PR TITLE
Added Xamarin support to the PCL nuspec

### PR DESCRIPTION
**Pull request by matthidinger**
Added more PCL configurations in the nuspec file, to enable MonoTouch10
(iOS), and MonoAndroid10 (Android)

### CODE REVIEW

**Comment by michielpost** [comment]
Thanks!

**Comment by matthidinger** [comment]
No problem,  thanks for this awesome API! It worked great in a Xamarin Android project I've been working on

**Comment by michielpost** [comment]
New version with this change is available on NuGet: https://www.nuget.org/packages/Q42.HueApi/

**Comment by michielpost** [comment]
Is the Android app publicly available in the Play Store? If so, I can include it in the "Apps that use Q42.HueAPI" list in the readme.

**Pull request merged**
