### PR TITLE
Refactor, unit test color conversion

### PR DESCRIPTION
**Pull request by patrickmeiring**

### CODE REVIEW

**Comment by patrickmeiring** [comment]
Hey Guys,
Until now, I've been maintaining a copy of Q42.HueApi without the color-conversion arrays (in my attempt to reduce the size of my app package and improve start-up time). 

I thought it might be useful to clean-up the color conversion class and make everything use a consistent mathematical way of converting between CIE1931 and RGB color spaces. 

In the process of doing this, I've uncovered a couple of bugs in the existing implementation, such as this one on line 660 of HueColorConverter:
```C#
		return new RGBColor() { R = (byte)r, G = (byte)g, B = (byte)b, A = (byte)1.0f };"
```
(Given r, g and b are floats between 0.0 and 1.0, the effect of this is to make all converted RGB colors have red, green and blue components of exactly 0 or 1 ... which makes me think nobody is using this particular function at the moment.)

I realise there's a lot of code change in the commit, so I'm happy to answer any questions you have...

**Comment by michielpost** [comment]
Thanks, great stuff. 
Some of the color conversion stuff is hocus pocus to me. But as you say, the current implementation contains bugs and is not used much. Your version includes unit tests and is used and tested by you, so that already makes it a lot better.

Going to merge this!

**Comment by michielpost** [comment]
New packages are up on NuGet!

**Comment by patrickmeiring** [comment]
Awesome, thanks!

**Pull request merged**
